version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: "nginx:${NGINX_VERSION}"
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_CONFIG_PATH}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SITES_AVAILABLE}:/etc/nginx/sites-available:rw
      - ${NGINX_SITES_ENABLED}:/etc/nginx/sites-enabled:rw
      - ${NGINX_LOG_PATH}:/var/log/nginx:rw
